Update CONFIGURATION.md - added a note to `External forwarding`
buerokratt/Ruuter pull request #156
Opened 2023-05-14 23:21 UTC by Kristjanmn

2023-05-24 10:23 UTC, turnerrainer requested changes
Please add the functionality to pass Ruuter request URL (where the request was originally made to before sending it to an external endpoint) as part of the passed request

2023-06-15 19:54 UTC, RayDNoper approved these changes

2023-06-15 19:54 UTC, RayDNoper approved these changes

2023-06-15 19:55 UTC, RayDNoper approved these changes

2023-06-19 06:15 UTC, RayDNoper commented
Merged to main, additional functionality should be moved to a new issue.

2023-06-19 06:15 UTC, merged