Feature/read configuration files
buerokratt/Ruuter pull request #29
Opened 2022-05-31 08:22 UTC by ewertub

2022-06-01 05:44 UTC, turnerrainer approved these changes

2022-06-01 06:34 UTC, tonistuulNG requested changes

2022-06-01 06:34 UTC, tonistuulNG commented on build.gradle
> +    implementation 'junit:junit:4.13.1'
miks meile mingi vana tehnoloogia kui meil on junit 5 (jupiter)?

2022-06-01 06:34 UTC, tonistuulNG commented on src/main/java/ee/buerokratt/ruuter/RuuterApplication.java
> +    @EventListener(ApplicationReadyEvent.class)
configuratsioonide laadimine võiks varem toimuda, sest applicationReady ütleb sisuliselt, et rakendus on valmis päringuid vastu võtma - kui konfid pole sees, siis tegelikult ju ei ole valmis

2022-06-01 06:34 UTC, tonistuulNG commented on src/main/resources/application.properties
> +ruuter.config.path=\${user.dir}/configurations
properties -> yml

2022-06-02 08:44 UTC, ewertub commented
new pull request [https://github.com/buerokratt/Ruuter/pull/33](url) was created from this.

2022-06-02 08:44 UTC, closed without merging