test: 22 add tests for string concatenation and scripting helper over all
buerokratt/Ruuter pull request #57
Opened 2022-06-28 08:05 UTC by ewertub

Add tests for string concatenation

2022-06-28 08:10 UTC, henrikprangelNG requested changes

2022-06-28 08:10 UTC, henrikprangelNG commented on src/test/resources/helper/boolean-or-evaluation.yml
> +concatenateStrings:
Sul praegu kaks erinevat stiili steppide nimetamiseks: camelCase ja snake_case. Kuna meil kõik senised confid on olnud snake case'is, siis kasutame pigem seda.

2022-06-29 07:22 UTC, henrikprangelNG approved these changes

2022-06-29 09:56 UTC, turnerrainer approved these changes

2022-06-29 09:58 UTC, merged