feat: 36 add subcategories to /ruuter/services/ folder
buerokratt/Ruuter pull request #64
Opened 2022-07-01 11:44 UTC by ewertub

Add subcategories to /ruuter/services/ folder

2022-07-01 13:37 UTC, henrikprangelNG requested changes

2022-07-01 13:37 UTC, henrikprangelNG commented on src/main/java/ee/buerokratt/ruuter/service/ConfigurationService.java
> +    public Map<String, Map<String, Map<String, ConfigurationStep>>> getConfigurations(String configPath) {
I think the following solution would be a bit cleaner:
```
    public Map<String, Map<String, Map<String, ConfigurationStep>>> getConfigurations(String configPath) {
        return Arrays.stream(Objects.requireNonNull(new File(configPath).listFiles(File::isDirectory))).collect(toMap(File::getName, directory -> {
            try (Stream<Path> paths = Files.walk(getFolderPath(directory.toString()))) {
                return paths
                    .filter(Files::isRegularFile)
                    .collect(toMap(FileUtils::getFileNameWithoutSuffix, configurationMappingHelper::getConfigurationSteps));
            } catch (Exception e) {
                throw new LoadConfigurationsException(e);
            }
        }));
    }
```

2022-07-05 03:01 UTC, turnerrainer approved these changes

2022-07-08 08:19 UTC, henrikprangelNG approved these changes

2022-07-08 10:51 UTC, merged