feat: 42 Add sleep functionality to steps
buerokratt/Ruuter pull request #74
Opened 2022-07-11 09:15 UTC by henrikprangelNG

Added sleep functionality to steps (defined in `ms`)

2022-07-11 09:16 UTC, henrikprangelNG commented
@turnerrainer - will add the readme portion as soon as i have an anwser to this question:
https://github.com/buerokratt/Ruuter/issues/70#issuecomment-1180158516

2022-07-11 23:59 UTC, turnerrainer requested changes
Please add a sample YAML as well

2022-07-12 10:23 UTC, henrikprangelNG commented
> Please add a sample YAML as well

Added an example yml - will link it with readme/guide in: https://github.com/buerokratt/Ruuter/issues/71

2022-07-12 10:34 UTC, ewertub approved these changes

2022-07-12 20:15 UTC, turnerrainer approved these changes

2022-07-13 08:18 UTC, merged