Chore/71 sample dsls as default services to cover all functionalities
buerokratt/Ruuter pull request #79
Opened 2022-07-14 11:57 UTC by henrikprangelNG

Add samples for all steps and functionalities

2022-07-15 05:52 UTC, ewertub requested changes

2022-07-15 05:52 UTC, ewertub commented on samples/steps/template.md
>    params:
```suggestion
  query:
```

2022-07-15 05:52 UTC, ewertub commented on DSL/GET/steps/template/template-with-params.yml
> +  params:
```suggestion
  query:
```

2022-07-25 09:55 UTC, turnerrainer approved these changes

2022-07-29 13:02 UTC, merged