refactor: 81 change configuration/service to dsl and add requestType to DefaultHttpDsl
buerokratt/Ruuter pull request #82
Opened 2022-07-15 08:04 UTC by ewertub

Refactor configuration/service to dsl

2022-07-15 11:12 UTC, henrikprangelNG requested changes

2022-07-15 11:12 UTC, henrikprangelNG commented on src/main/java/ee/buerokratt/ruuter/controller/DslController.java
> +    @RequestMapping(value = "/{dsl}")
Update the GUIDE as well, to reference the new `/{dsl}` instead of the old `/configuration`

2022-07-15 11:12 UTC, henrikprangelNG commented on src/main/java/ee/buerokratt/ruuter/domain/steps/http/HttpStep.java
> +    private boolean isNotAllowedHttpStatusCode(DslInstance di, Integer response) {
"negative" functions are harder to read and understand than positive ones. Leave this as "isAllowed..." and simply reverse the result with `!` where you need to use the negated value.

2022-07-25 07:31 UTC, ainkivimagi approved these changes

2022-07-25 09:51 UTC, turnerrainer approved these changes

2022-07-26 06:53 UTC, merged